# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: psicologomiguelcoria.github.io
title: Psicologo Miguel Coria
email: 
author: Psicologo Miguel Coria
description: > # "Como profesional en psicología clínica, brindo servicio de psicoterapia especializada en el modelo cognitivo conductual.También ofrezco mis servicios de psicoterapia a distancia por medio de video llamada.. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2024 Your Name. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com
  - title: github
    url: 
  - title: linkedin
    url: 
